name: AI Issue Tracker

on:
  push:
    branches:
      - main

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Issue Detector
        run: python .github/scripts/issue_tracker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
